import {BadRequestException,ForbiddenException,Injectable,NotFoundException} from '@nestjs/common';
import {addDecimals,cashSaleJournal,compareDecimals,multiplyDecimals,prorateDecimal,saleRefundJournal,subtractDecimals} from '@mohammedsaas/accounting-engine';
import {PERMISSIONS} from '@mohammedsaas/permissions';
import type {PosSaleLookupDto,PosShiftSummaryDto,TenantContext} from '@mohammedsaas/types';
import type {Prisma} from '../../generated/prisma/client.js';
import {PrismaService} from '../../infra/prisma/prisma.service.js';
import {InventoryService} from '../inventory/inventory.service.js';
import {AccountingService} from '../accounting/accounting.service.js';

type PaymentMethod='CASH'|'CARD'|'BANK_TRANSFER'|'OTHER';
type RefundInput={shiftId:string;warehouseId:string;reason:string;idempotencyKey:string;items:Array<{invoiceItemId:string;quantity:string}>};

@Injectable()
export class SalesService{
  constructor(private readonly prisma:PrismaService,private readonly inventory:InventoryService,private readonly accounting:AccountingService){}

  invoices(context:TenantContext,page:number){const pageSize=25,current=Number.isFinite(page)&&page>0?Math.floor(page):1;return this.prisma.forTenant(context.tenantId,async tx=>{const where={tenantId:context.tenantId,branchId:{in:context.branchIds}};const[data,total]=await Promise.all([tx.salesInvoice.findMany({where,include:{customer:{select:{id:true,name:true}},items:true},orderBy:{createdAt:'desc'},skip:(current-1)*pageSize,take:pageSize}),tx.salesInvoice.count({where})]);return{data,total,page:current,pageSize};});}

  currentShift(context:TenantContext,branchId?:string){if(branchId&&!context.branchIds.includes(branchId))throw new ForbiddenException('Branch access denied');return this.prisma.forTenant(context.tenantId,async tx=>{const shift=await tx.cashierShift.findFirst({where:{tenantId:context.tenantId,openedById:context.userId,status:'OPEN',...(branchId?{branchId}:{branchId:{in:context.branchIds}})},orderBy:{openedAt:'desc'}});return shift?this.buildShiftSummary(tx,context,shift.id):null;});}

  shiftSummary(context:TenantContext,shiftId:string){return this.prisma.forTenant(context.tenantId,async tx=>{const shift=await tx.cashierShift.findFirst({where:{id:shiftId,tenantId:context.tenantId,openedById:context.userId,branchId:{in:context.branchIds}}});if(!shift)throw new NotFoundException('Shift not found');return this.buildShiftSummary(tx,context,shift.id);});}

  openShift(context:TenantContext,input:{branchId:string;openingCash:string}){if(!context.branchIds.includes(input.branchId))throw new ForbiddenException('Branch access denied');if(compareDecimals(input.openingCash,'0.0000')<0)throw new BadRequestException('Opening cash cannot be negative');return this.prisma.forTenant(context.tenantId,async tx=>{const existing=await tx.cashierShift.findFirst({where:{tenantId:context.tenantId,branchId:input.branchId,openedById:context.userId,status:'OPEN'}});if(existing)return this.buildShiftSummary(tx,context,existing.id);const shift=await tx.cashierShift.create({data:{tenantId:context.tenantId,branchId:input.branchId,openedById:context.userId,openingCash:input.openingCash,status:'OPEN'}});await tx.auditLog.create({data:{tenantId:context.tenantId,actorId:context.userId,branchId:input.branchId,action:'cashier_shift_opened',entityType:'cashier_shift',entityId:shift.id}});return this.buildShiftSummary(tx,context,shift.id);});}

  closeShift(context:TenantContext,shiftId:string,countedCash:string){if(compareDecimals(countedCash,'0.0000')<0)throw new BadRequestException('Counted cash cannot be negative');return this.prisma.forTenant(context.tenantId,async tx=>{await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`shift:${context.tenantId}:${shiftId}`},0))`;const shift=await tx.cashierShift.findFirst({where:{id:shiftId,tenantId:context.tenantId,openedById:context.userId,status:'OPEN'}});if(!shift)throw new NotFoundException('Open shift not found');if(!context.branchIds.includes(shift.branchId))throw new ForbiddenException('Branch access denied');const summary=await this.buildShiftSummary(tx,context,shift.id);const difference=subtractDecimals(countedCash,summary.expectedCash);await tx.cashierShift.update({where:{id:shift.id},data:{status:'CLOSED',closedAt:new Date(),closedById:context.userId,expectedCash:summary.expectedCash,countedCash,cashVariance:difference}});await tx.auditLog.create({data:{tenantId:context.tenantId,actorId:context.userId,branchId:shift.branchId,action:'cashier_shift_closed',entityType:'cashier_shift',entityId:shift.id,metadata:{expectedCash:summary.expectedCash,countedCash,difference}}});return this.buildShiftSummary(tx,context,shift.id);});}

  findPosInvoice(context:TenantContext,number:string){if(!number.trim())throw new BadRequestException('Invoice number required');return this.prisma.forTenant(context.tenantId,async tx=>{const invoice=await tx.salesInvoice.findFirst({where:{tenantId:context.tenantId,branchId:{in:context.branchIds},number:number.trim(),posTransaction:{isNot:null}},include:{items:true,customer:{select:{id:true,name:true}},posTransaction:true,salesReturns:{include:{items:true}}}});return invoice?this.toPosSaleLookup(invoice):null;});}

  completePosSale(context:TenantContext,input:{branchId:string;warehouseId:string;shiftId:string;customerId?:string;paymentMethod:PaymentMethod;idempotencyKey:string;items:Array<{productId:string;quantity:string;discount:string}>}){
    if(!context.branchIds.includes(input.branchId))throw new ForbiddenException('Branch access denied');
    if(input.items.some(item=>compareDecimals(item.discount,'0.0000')>0)&&!context.permissions.includes(PERMISSIONS.POS_DISCOUNT))throw new ForbiddenException('Discount permission required');
    return this.prisma.forTenant(context.tenantId,async tx=>{
      const replay=await tx.salesInvoice.findFirst({where:{tenantId:context.tenantId,idempotencyKey:input.idempotencyKey},include:{items:true,payments:true}});if(replay)return{invoice:replay,idempotentReplay:true};
      const shift=await tx.cashierShift.findFirst({where:{id:input.shiftId,tenantId:context.tenantId,branchId:input.branchId,openedById:context.userId,status:'OPEN'}});if(!shift)throw new BadRequestException('Authenticated cashier must have an open shift');
      if(!await tx.warehouse.findFirst({where:{id:input.warehouseId,tenantId:context.tenantId,branchId:input.branchId,active:true}}))throw new BadRequestException('Warehouse does not belong to branch');
      if(input.customerId&&!await tx.customer.findFirst({where:{id:input.customerId,tenantId:context.tenantId,active:true}}))throw new BadRequestException('Customer not found');
      const productIds=[...new Set(input.items.map(item=>item.productId))];const products=await tx.product.findMany({where:{tenantId:context.tenantId,id:{in:productIds},active:true}}),byId=new Map(products.map(product=>[product.id,product]));if(products.length!==productIds.length)throw new BadRequestException('Product unavailable');
      let subtotal='0.0000',discountTotal='0.0000',taxTotal='0.0000',cost='0.0000';const lines:Array<{productId:string;description:string;quantity:string;unitPrice:string;unitCost:string;discount:string;tax:string;lineTotal:string}>=[];
      for(const item of input.items){if(compareDecimals(item.quantity,'0.0000')<=0)throw new BadRequestException('Quantity must be positive');const product=byId.get(item.productId)!;if(product.trackInventory){await this.inventory.lockStock(tx,context.tenantId,input.warehouseId,product.id);await this.inventory.assertAvailable(tx,context.tenantId,input.warehouseId,product.id,item.quantity);}const gross=multiplyDecimals(item.quantity,product.sellingPrice.toString());if(compareDecimals(item.discount,gross)>0)throw new BadRequestException('Discount exceeds line amount');const net=subtractDecimals(gross,item.discount),tax=multiplyDecimals(net,product.taxRate.toString()),lineTotal=addDecimals(net,tax);subtotal=addDecimals(subtotal,gross);discountTotal=addDecimals(discountTotal,item.discount);taxTotal=addDecimals(taxTotal,tax);cost=addDecimals(cost,multiplyDecimals(item.quantity,product.costPrice.toString()));lines.push({productId:product.id,description:product.name,quantity:item.quantity,unitPrice:product.sellingPrice.toString(),unitCost:product.costPrice.toString(),discount:item.discount,tax,lineTotal});}
      const net=subtractDecimals(subtotal,discountTotal),total=addDecimals(net,taxTotal),sequence=await tx.tenantSequence.upsert({where:{tenantId_key:{tenantId:context.tenantId,key:'INV'}},create:{tenantId:context.tenantId,key:'INV',value:1n},update:{value:{increment:1}}}),currency=(await tx.tenant.findUniqueOrThrow({where:{id:context.tenantId},select:{baseCurrency:true}})).baseCurrency;
      const invoice=await tx.salesInvoice.create({data:{tenantId:context.tenantId,branchId:input.branchId,number:`INV-${sequence.value.toString().padStart(6,'0')}`,status:'PAID',currency,subtotal,discountTotal,taxTotal,total,paidAmount:total,idempotencyKey:input.idempotencyKey,postedAt:new Date(),createdById:context.userId,...(input.customerId?{customerId:input.customerId}:{}),items:{create:lines}},include:{items:true}});
      for(const line of lines)if(byId.get(line.productId)!.trackInventory)await tx.inventoryMovement.create({data:{tenantId:context.tenantId,branchId:input.branchId,warehouseId:input.warehouseId,productId:line.productId,quantity:line.quantity,direction:'OUT',type:'SALE',referenceType:'SALES_INVOICE',referenceId:invoice.id,createdById:context.userId}});
      const account=input.paymentMethod==='CASH'||input.paymentMethod==='OTHER'?'1100':'1200';const payment=await tx.customerPayment.create({data:{tenantId:context.tenantId,...(input.customerId?{customerId:input.customerId}:{}),invoiceId:invoice.id,amount:total,currency,method:input.paymentMethod,accountCode:account,receivedAt:new Date()}});await tx.posTransaction.create({data:{tenantId:context.tenantId,branchId:input.branchId,shiftId:input.shiftId,invoiceId:invoice.id,total,method:input.paymentMethod}});await this.accounting.postJournal(tx,{tenantId:context.tenantId,sourceType:'POS_SALE',sourceId:invoice.id,entryDate:new Date(),draft:cashSaleJournal({net,tax:taxTotal,cost,currency,debitAccountCode:account})});await tx.auditLog.create({data:{tenantId:context.tenantId,actorId:context.userId,branchId:input.branchId,action:'pos_sale_completed',entityType:'sales_invoice',entityId:invoice.id,metadata:{invoiceNumber:invoice.number,total,customerId:input.customerId??null,discountTotal}}});return{invoice,payment,idempotentReplay:false};
    });
  }

  refundPosSale(context:TenantContext,invoiceId:string,input:RefundInput){
    return this.prisma.forTenant(context.tenantId,async tx=>{
      await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`refund:${context.tenantId}:${invoiceId}`},0))`;
      const replay=await tx.salesReturn.findFirst({where:{tenantId:context.tenantId,idempotencyKey:input.idempotencyKey},include:{items:true}});if(replay)return{salesReturn:replay,idempotentReplay:true};
      const invoice=await tx.salesInvoice.findFirst({where:{id:invoiceId,tenantId:context.tenantId},include:{items:true,posTransaction:true,salesReturns:{include:{items:true}}}});if(!invoice)throw new NotFoundException('Invoice not found');if(!context.branchIds.includes(invoice.branchId))throw new ForbiddenException('Branch access denied');if(!invoice.posTransaction||!['PAID','REFUNDED'].includes(invoice.status))throw new BadRequestException('Only posted POS sales can be refunded');
      const shift=await tx.cashierShift.findFirst({where:{id:input.shiftId,tenantId:context.tenantId,branchId:invoice.branchId,openedById:context.userId,status:'OPEN'}});if(!shift)throw new BadRequestException('Authenticated cashier must have an open shift');if(!await tx.warehouse.findFirst({where:{id:input.warehouseId,tenantId:context.tenantId,branchId:invoice.branchId,active:true}}))throw new BadRequestException('Warehouse invalid');
      const requestedIds=input.items.map(item=>item.invoiceItemId);if(new Set(requestedIds).size!==requestedIds.length)throw new BadRequestException('Duplicate refund line');
      let refundNet='0.0000',refundTax='0.0000',refundCost='0.0000',refundTotal='0.0000';const returnLines:Array<{invoiceItemId:string;productId:string;quantity:string;netAmount:string;taxAmount:string;costAmount:string;totalAmount:string}>=[];
      for(const request of input.items){if(compareDecimals(request.quantity,'0.0000')<=0)throw new BadRequestException('Refund quantity must be positive');const line=invoice.items.find(item=>item.id===request.invoiceItemId);if(!line)throw new BadRequestException('Refund line does not belong to invoice');const priorItems=invoice.salesReturns.flatMap(salesReturn=>salesReturn.items).filter(item=>item.invoiceItemId===line.id);const priorQuantity=priorItems.reduce((sum,item)=>addDecimals(sum,item.quantity.toString()),'0.0000'),available=subtractDecimals(line.quantity.toString(),priorQuantity);if(compareDecimals(request.quantity,available)>0)throw new BadRequestException('Refund quantity exceeds refundable quantity');const originalNet=subtractDecimals(line.lineTotal.toString(),line.tax.toString()),priorNet=priorItems.reduce((sum,item)=>addDecimals(sum,item.netAmount.toString()),'0.0000'),priorTax=priorItems.reduce((sum,item)=>addDecimals(sum,item.taxAmount.toString()),'0.0000');const isFinal=compareDecimals(request.quantity,available)===0;const net=isFinal?subtractDecimals(originalNet,priorNet):prorateDecimal(originalNet,request.quantity,line.quantity.toString()),tax=isFinal?subtractDecimals(line.tax.toString(),priorTax):prorateDecimal(line.tax.toString(),request.quantity,line.quantity.toString()),cost=multiplyDecimals(request.quantity,line.unitCost.toString()),total=addDecimals(net,tax);refundNet=addDecimals(refundNet,net);refundTax=addDecimals(refundTax,tax);refundCost=addDecimals(refundCost,cost);refundTotal=addDecimals(refundTotal,total);returnLines.push({invoiceItemId:line.id,productId:line.productId,quantity:request.quantity,netAmount:net,taxAmount:tax,costAmount:cost,totalAmount:total});}
      const salesReturn=await tx.salesReturn.create({data:{tenantId:context.tenantId,branchId:invoice.branchId,invoiceId:invoice.id,shiftId:input.shiftId,amount:refundTotal,currency:invoice.currency,method:invoice.posTransaction.method,reason:input.reason,idempotencyKey:input.idempotencyKey,createdById:context.userId,items:{create:returnLines}},include:{items:true}});
      for(const line of returnLines){await this.inventory.lockStock(tx,context.tenantId,input.warehouseId,line.productId);await tx.inventoryMovement.create({data:{tenantId:context.tenantId,branchId:invoice.branchId,warehouseId:input.warehouseId,productId:line.productId,quantity:line.quantity,direction:'IN',type:'SALE_RETURN',referenceType:'SALES_RETURN',referenceId:salesReturn.id,createdById:context.userId,reason:input.reason}});}
      const account=invoice.posTransaction.method==='CASH'||invoice.posTransaction.method==='OTHER'?'1100':'1200';await this.accounting.postJournal(tx,{tenantId:context.tenantId,sourceType:'POS_REFUND',sourceId:salesReturn.id,entryDate:new Date(),draft:saleRefundJournal({net:refundNet,tax:refundTax,cost:refundCost,currency:invoice.currency,creditAccountCode:account})});
      const allReturns=[...invoice.salesReturns,{...salesReturn,items:salesReturn.items}],fullyRefunded=invoice.items.every(line=>{const returned=allReturns.flatMap(salesReturn=>salesReturn.items).filter(item=>item.invoiceItemId===line.id).reduce((sum,item)=>addDecimals(sum,item.quantity.toString()),'0.0000');return compareDecimals(returned,line.quantity.toString())===0;});if(fullyRefunded)await tx.salesInvoice.update({where:{id:invoice.id},data:{status:'REFUNDED'}});
      await tx.auditLog.create({data:{tenantId:context.tenantId,actorId:context.userId,branchId:invoice.branchId,action:'pos_sale_refunded',entityType:'sales_invoice',entityId:invoice.id,metadata:{returnId:salesReturn.id,amount:refundTotal,reason:input.reason,items:input.items}}});return{salesReturn,idempotentReplay:false};
    });
  }

  private toPosSaleLookup(invoice:{id:string;number:string;status:string;currency:string;total:{toString():string};customer:{id:string;name:string}|null;posTransaction:{method:PaymentMethod}|null;items:Array<{id:string;productId:string;description:string;quantity:{toString():string};unitPrice:{toString():string};discount:{toString():string};tax:{toString():string};lineTotal:{toString():string}}>;salesReturns:Array<{items:Array<{invoiceItemId:string;quantity:{toString():string}>}>}>}):PosSaleLookupDto{if(!invoice.posTransaction)throw new BadRequestException('POS transaction missing');return{invoiceId:invoice.id,number:invoice.number,status:invoice.status,currency:invoice.currency,total:invoice.total.toString(),customer:invoice.customer,paymentMethod:invoice.posTransaction.method,lines:invoice.items.map(line=>{const refunded=invoice.salesReturns.flatMap(salesReturn=>salesReturn.items).filter(item=>item.invoiceItemId===line.id).reduce((sum,item)=>addDecimals(sum,item.quantity.toString()),'0.0000');return{invoiceItemId:line.id,productId:line.productId,description:line.description,soldQuantity:line.quantity.toString(),refundedQuantity:refunded,refundableQuantity:subtractDecimals(line.quantity.toString(),refunded),unitPrice:line.unitPrice.toString(),discount:line.discount.toString(),tax:line.tax.toString(),lineTotal:line.lineTotal.toString()};})};}

  private async buildShiftSummary(tx:Prisma.TransactionClient,context:TenantContext,shiftId:string):Promise<PosShiftSummaryDto>{const shift=await tx.cashierShift.findFirst({where:{id:shiftId,tenantId:context.tenantId,openedById:context.userId,branchId:{in:context.branchIds}}});if(!shift)throw new NotFoundException('Shift not found');const[cash,nonCash,refunds,cashRefunds]=await Promise.all([tx.posTransaction.aggregate({where:{tenantId:context.tenantId,shiftId,method:'CASH'},_sum:{total:true}}),tx.posTransaction.aggregate({where:{tenantId:context.tenantId,shiftId,method:{not:'CASH'}},_sum:{total:true}}),tx.salesReturn.aggregate({where:{tenantId:context.tenantId,shiftId},_sum:{amount:true}}),tx.salesReturn.aggregate({where:{tenantId:context.tenantId,shiftId,method:'CASH'},_sum:{amount:true}})]);const cashSales=cash._sum.total?.toString()??'0.0000',nonCashSales=nonCash._sum.total?.toString()??'0.0000',refundTotal=refunds._sum.amount?.toString()??'0.0000',cashRefundTotal=cashRefunds._sum.amount?.toString()??'0.0000',expectedCash=subtractDecimals(addDecimals(shift.openingCash.toString(),cashSales),cashRefundTotal),countedCash=shift.countedCash?.toString()??null,difference=shift.cashVariance?.toString()??(countedCash?subtractDecimals(countedCash,expectedCash):null);return{id:shift.id,branchId:shift.branchId,status:shift.status,openingCash:shift.openingCash.toString(),cashSales,nonCashSales,refunds:refundTotal,cashRefunds:cashRefundTotal,expectedCash,countedCash,difference,openedAt:shift.openedAt.toISOString(),closedAt:shift.closedAt?.toISOString()??null};}
}
