export const PERMISSIONS={
 SALES_VIEW:'sales.view',SALES_CREATE:'sales.create',SALES_UPDATE:'sales.update',SALES_CANCEL:'sales.cancel',INVOICES_VIEW:'invoices.view',INVOICES_CREATE:'invoices.create',INVOICES_POST:'invoices.post',INVOICES_REFUND:'invoices.refund',
 INVENTORY_VIEW:'inventory.view',INVENTORY_RECEIVE:'inventory.receive',INVENTORY_TRANSFER:'inventory.transfer',INVENTORY_ADJUST:'inventory.adjust',CUSTOMERS_VIEW:'customers.view',CUSTOMERS_CREATE:'customers.create',CUSTOMERS_UPDATE:'customers.update',
 SUPPLIERS_VIEW:'suppliers.view',SUPPLIERS_CREATE:'suppliers.create',SUPPLIERS_UPDATE:'suppliers.update',PRODUCTS_VIEW:'products.view',PRODUCTS_CREATE:'products.create',PRODUCTS_UPDATE:'products.update',PURCHASES_VIEW:'purchases.view',PURCHASES_CREATE:'purchases.create',PURCHASES_POST:'purchases.post',
 ACCOUNTING_VIEW:'accounting.view',JOURNAL_CREATE:'accounting.journal.create',JOURNAL_POST:'accounting.journal.post',PERIOD_CLOSE:'accounting.period.close',REPORTS_SALES:'reports.sales',REPORTS_INVENTORY:'reports.inventory',REPORTS_PROFIT:'reports.profit',REPORTS_FINANCIAL:'reports.financial',
 TEAM_VIEW:'team.view',TEAM_INVITE:'team.invite',TEAM_MANAGE_ROLES:'team.manage_roles',SETTINGS_VIEW:'settings.view',SETTINGS_UPDATE:'settings.update',POS_SELL:'pos.sell',POS_REFUND:'pos.refund',POS_DISCOUNT:'pos.discount',POS_OPEN_SHIFT:'pos.open_shift',POS_CLOSE_SHIFT:'pos.close_shift',
 BANKING_VIEW:'banking.view',BANKING_MANAGE:'banking.manage',EXPENSES_VIEW:'expenses.view',EXPENSES_CREATE:'expenses.create',BRANCHES_VIEW:'branches.view',BRANCHES_MANAGE:'branches.manage',SUBSCRIPTION_VIEW:'subscription.view'
} as const;
export type Permission=(typeof PERMISSIONS)[keyof typeof PERMISSIONS];
const all=Object.values(PERMISSIONS) as Permission[]; const pick=(...x:Permission[])=>x;
const BRANCH_MANAGER_DENIED=new Set<Permission>([PERMISSIONS.SUBSCRIPTION_VIEW,PERMISSIONS.TEAM_MANAGE_ROLES,PERMISSIONS.PERIOD_CLOSE]);
export const DEFAULT_ROLE_PERMISSIONS:Record<string,readonly Permission[]>={
 OWNER:all, ADMIN:all.filter(p=>p!==PERMISSIONS.SUBSCRIPTION_VIEW),
 ACCOUNTANT:pick(PERMISSIONS.ACCOUNTING_VIEW,PERMISSIONS.JOURNAL_CREATE,PERMISSIONS.JOURNAL_POST,PERMISSIONS.PERIOD_CLOSE,PERMISSIONS.REPORTS_FINANCIAL,PERMISSIONS.REPORTS_PROFIT,PERMISSIONS.BANKING_VIEW,PERMISSIONS.BANKING_MANAGE,PERMISSIONS.EXPENSES_VIEW,PERMISSIONS.EXPENSES_CREATE,PERMISSIONS.CUSTOMERS_VIEW,PERMISSIONS.SUPPLIERS_VIEW,PERMISSIONS.INVOICES_VIEW,PERMISSIONS.PURCHASES_VIEW),
 CASHIER:pick(PERMISSIONS.POS_SELL,PERMISSIONS.POS_REFUND,PERMISSIONS.POS_DISCOUNT,PERMISSIONS.POS_OPEN_SHIFT,PERMISSIONS.POS_CLOSE_SHIFT,PERMISSIONS.SALES_VIEW,PERMISSIONS.INVOICES_VIEW,PERMISSIONS.CUSTOMERS_VIEW,PERMISSIONS.CUSTOMERS_CREATE,PERMISSIONS.PRODUCTS_VIEW),
 SALES:pick(PERMISSIONS.SALES_VIEW,PERMISSIONS.SALES_CREATE,PERMISSIONS.SALES_UPDATE,PERMISSIONS.INVOICES_VIEW,PERMISSIONS.INVOICES_CREATE,PERMISSIONS.CUSTOMERS_VIEW,PERMISSIONS.CUSTOMERS_CREATE,PERMISSIONS.CUSTOMERS_UPDATE,PERMISSIONS.PRODUCTS_VIEW,PERMISSIONS.REPORTS_SALES),
 INVENTORY:pick(PERMISSIONS.INVENTORY_VIEW,PERMISSIONS.INVENTORY_RECEIVE,PERMISSIONS.INVENTORY_TRANSFER,PERMISSIONS.INVENTORY_ADJUST,PERMISSIONS.PRODUCTS_VIEW,PERMISSIONS.PRODUCTS_CREATE,PERMISSIONS.PRODUCTS_UPDATE,PERMISSIONS.REPORTS_INVENTORY),
 PURCHASING:pick(PERMISSIONS.PURCHASES_VIEW,PERMISSIONS.PURCHASES_CREATE,PERMISSIONS.PURCHASES_POST,PERMISSIONS.SUPPLIERS_VIEW,PERMISSIONS.SUPPLIERS_CREATE,PERMISSIONS.SUPPLIERS_UPDATE,PERMISSIONS.PRODUCTS_VIEW,PERMISSIONS.INVENTORY_RECEIVE),
 BRANCH_MANAGER:all.filter(p=>!BRANCH_MANAGER_DENIED.has(p))
};
export const hasPermission=(g:Iterable<string>,r:Permission)=>new Set(g).has(r);
export const hasEveryPermission=(g:Iterable<string>,r:readonly Permission[])=>{const s=new Set(g);return r.every(p=>s.has(p));};
