const SCALE=4n,FACTOR=10n**SCALE; const norm=(v:string)=>{const x=v.trim();if(!/^-?\d+(\.\d{1,4})?$/.test(x))throw new Error(`Invalid decimal amount: ${v}`);return x;};
export function decimalToUnits(raw:string):bigint{const v=norm(raw),neg=v.startsWith('-'),u=neg?v.slice(1):v,[whole='0',fraction='']=u.split('.');const n=BigInt(whole)*FACTOR+BigInt(fraction.padEnd(Number(SCALE),'0'));return neg?-n:n;}
export function unitsToDecimal(n:bigint):string{const neg=n<0n,a=neg?-n:n;return `${neg?'-':''}${a/FACTOR}.${(a%FACTOR).toString().padStart(4,'0')}`;}
export const addDecimals=(...v:string[])=>unitsToDecimal(v.reduce((s,x)=>s+decimalToUnits(x),0n)); export const subtractDecimals=(a:string,b:string)=>unitsToDecimal(decimalToUnits(a)-decimalToUnits(b)); export const multiplyDecimals=(a:string,b:string)=>unitsToDecimal((decimalToUnits(a)*decimalToUnits(b))/FACTOR); export const compareDecimals=(a:string,b:string)=>{const x=decimalToUnits(a),y=decimalToUnits(b);return x===y?0:x>y?1:-1;};
export type JournalLineInput=Readonly<{accountCode:string;debit:string;credit:string;memo?:string}>; export type JournalDraft=Readonly<{description:string;currency:string;lines:readonly JournalLineInput[]}>;
export function assertBalanced(lines:readonly JournalLineInput[]):void{if(lines.length<2)throw new Error('A journal entry requires at least two lines');let d=0n,c=0n;for(const l of lines){const x=decimalToUnits(l.debit),y=decimalToUnits(l.credit);if(x<0n||y<0n)throw new Error('Debit and credit must be non-negative');if(x>0n&&y>0n)throw new Error('A journal line cannot contain both debit and credit');if(x===0n&&y===0n)throw new Error('A journal line must contain a debit or credit');d+=x;c+=y;}if(d!==c)throw new Error(`Unbalanced journal: debit ${unitsToDecimal(d)} != credit ${unitsToDecimal(c)}`);}
export function cashSaleJournal(i:{net:string;tax:string;cost:string;currency:string;debitAccountCode?:string}):JournalDraft{const net=decimalToUnits(i.net),tax=decimalToUnits(i.tax),cost=decimalToUnits(i.cost);const lines:JournalLineInput[]=[{accountCode:i.debitAccountCode??'1100',debit:unitsToDecimal(net+tax),credit:'0.0000'},{accountCode:'4100',debit:'0.0000',credit:unitsToDecimal(net)}];if(tax>0n)lines.push({accountCode:'2200',debit:'0.0000',credit:unitsToDecimal(tax)});if(cost>0n)lines.push({accountCode:'5000',debit:unitsToDecimal(cost),credit:'0.0000'},{accountCode:'1400',debit:'0.0000',credit:unitsToDecimal(cost)});assertBalanced(lines);return{description:'Cash sale',currency:i.currency,lines};}
export function creditSaleJournal(i:{net:string;tax:string;cost:string;currency:string}):JournalDraft{const net=decimalToUnits(i.net),tax=decimalToUnits(i.tax),cost=decimalToUnits(i.cost);const lines:JournalLineInput[]=[{accountCode:'1300',debit:unitsToDecimal(net+tax),credit:'0.0000'},{accountCode:'4100',debit:'0.0000',credit:unitsToDecimal(net)}];if(tax>0n)lines.push({accountCode:'2200',debit:'0.0000',credit:unitsToDecimal(tax)});if(cost>0n)lines.push({accountCode:'5000',debit:unitsToDecimal(cost),credit:'0.0000'},{accountCode:'1400',debit:'0.0000',credit:unitsToDecimal(cost)});assertBalanced(lines);return{description:'Credit sale',currency:i.currency,lines};}
export function customerPaymentJournal(i:{amount:string;currency:string;cashAccountCode?:string}):JournalDraft{const a=unitsToDecimal(decimalToUnits(i.amount)),lines=[{accountCode:i.cashAccountCode??'1100',debit:a,credit:'0.0000'},{accountCode:'1300',debit:'0.0000',credit:a}];assertBalanced(lines);return{description:'Customer payment',currency:i.currency,lines};}
export function purchaseOnCreditJournal(i:{inventory:string;tax:string;currency:string}):JournalDraft{const inv=decimalToUnits(i.inventory),tax=decimalToUnits(i.tax);const lines:JournalLineInput[]=[{accountCode:'1400',debit:unitsToDecimal(inv),credit:'0.0000'},{accountCode:'2100',debit:'0.0000',credit:unitsToDecimal(inv+tax)}];if(tax>0n)lines.push({accountCode:'2210',debit:unitsToDecimal(tax),credit:'0.0000'});assertBalanced(lines);return{description:'Inventory purchase on credit',currency:i.currency,lines};}
export function supplierPaymentJournal(i:{amount:string;currency:string;cashAccountCode?:string}):JournalDraft{const a=unitsToDecimal(decimalToUnits(i.amount)),lines=[{accountCode:'2100',debit:a,credit:'0.0000'},{accountCode:i.cashAccountCode??'1100',debit:'0.0000',credit:a}];assertBalanced(lines);return{description:'Supplier payment',currency:i.currency,lines};}
export function expenseJournal(i:{amount:string;tax:string;currency:string;expenseAccountCode?:string;cashAccountCode?:string}):JournalDraft{const amount=decimalToUnits(i.amount),tax=decimalToUnits(i.tax);const lines:JournalLineInput[]=[{accountCode:i.expenseAccountCode??'6000',debit:unitsToDecimal(amount),credit:'0.0000'},{accountCode:i.cashAccountCode??'1100',debit:'0.0000',credit:unitsToDecimal(amount+tax)}];if(tax>0n)lines.push({accountCode:'2210',debit:unitsToDecimal(tax),credit:'0.0000'});assertBalanced(lines);return{description:'Expense paid',currency:i.currency,lines};}
