const SCALE=4n;
const FACTOR=10n**SCALE;
const normalize=(value:string)=>{const input=value.trim();if(!/^-?\d+(\.\d{1,4})?$/.test(input))throw new Error(`Invalid decimal amount: ${value}`);return input;};

export function decimalToUnits(raw:string):bigint{const value=normalize(raw),negative=value.startsWith('-'),unsigned=negative?value.slice(1):value,[whole='0',fraction='']=unsigned.split('.');const units=BigInt(whole)*FACTOR+BigInt(fraction.padEnd(Number(SCALE),'0'));return negative?-units:units;}
export function unitsToDecimal(units:bigint):string{const negative=units<0n,absolute=negative?-units:units;return `${negative?'-':''}${absolute/FACTOR}.${(absolute%FACTOR).toString().padStart(4,'0')}`;}
export const addDecimals=(...values:string[])=>unitsToDecimal(values.reduce((sum,value)=>sum+decimalToUnits(value),0n));
export const subtractDecimals=(a:string,b:string)=>unitsToDecimal(decimalToUnits(a)-decimalToUnits(b));
export const multiplyDecimals=(a:string,b:string)=>unitsToDecimal((decimalToUnits(a)*decimalToUnits(b))/FACTOR);
export const compareDecimals=(a:string,b:string)=>{const left=decimalToUnits(a),right=decimalToUnits(b);return left===right?0:left>right?1:-1;};
export function prorateDecimal(total:string,part:string,whole:string):string{const denominator=decimalToUnits(whole);if(denominator<=0n)throw new Error('Proration denominator must be positive');return unitsToDecimal((decimalToUnits(total)*decimalToUnits(part))/denominator);}

export type JournalLineInput=Readonly<{accountCode:string;debit:string;credit:string;memo?:string}>;
export type JournalDraft=Readonly<{description:string;currency:string;lines:readonly JournalLineInput[]}>;

export function assertBalanced(lines:readonly JournalLineInput[]):void{if(lines.length<2)throw new Error('A journal entry requires at least two lines');let debit=0n,credit=0n;for(const line of lines){const d=decimalToUnits(line.debit),c=decimalToUnits(line.credit);if(d<0n||c<0n)throw new Error('Debit and credit must be non-negative');if(d>0n&&c>0n)throw new Error('A journal line cannot contain both debit and credit');if(d===0n&&c===0n)throw new Error('A journal line must contain a debit or credit');debit+=d;credit+=c;}if(debit!==credit)throw new Error(`Unbalanced journal: debit ${unitsToDecimal(debit)} != credit ${unitsToDecimal(credit)}`);}

export function cashSaleJournal(input:{net:string;tax:string;cost:string;currency:string;debitAccountCode?:string}):JournalDraft{const net=decimalToUnits(input.net),tax=decimalToUnits(input.tax),cost=decimalToUnits(input.cost);const lines:JournalLineInput[]=[{accountCode:input.debitAccountCode??'1100',debit:unitsToDecimal(net+tax),credit:'0.0000'},{accountCode:'4100',debit:'0.0000',credit:unitsToDecimal(net)}];if(tax>0n)lines.push({accountCode:'2200',debit:'0.0000',credit:unitsToDecimal(tax)});if(cost>0n)lines.push({accountCode:'5000',debit:unitsToDecimal(cost),credit:'0.0000'},{accountCode:'1400',debit:'0.0000',credit:unitsToDecimal(cost)});assertBalanced(lines);return{description:'Cash sale',currency:input.currency,lines};}
export function creditSaleJournal(input:{net:string;tax:string;cost:string;currency:string}):JournalDraft{const net=decimalToUnits(input.net),tax=decimalToUnits(input.tax),cost=decimalToUnits(input.cost);const lines:JournalLineInput[]=[{accountCode:'1300',debit:unitsToDecimal(net+tax),credit:'0.0000'},{accountCode:'4100',debit:'0.0000',credit:unitsToDecimal(net)}];if(tax>0n)lines.push({accountCode:'2200',debit:'0.0000',credit:unitsToDecimal(tax)});if(cost>0n)lines.push({accountCode:'5000',debit:unitsToDecimal(cost),credit:'0.0000'},{accountCode:'1400',debit:'0.0000',credit:unitsToDecimal(cost)});assertBalanced(lines);return{description:'Credit sale',currency:input.currency,lines};}
export function customerPaymentJournal(input:{amount:string;currency:string;cashAccountCode?:string}):JournalDraft{const amount=unitsToDecimal(decimalToUnits(input.amount)),lines:JournalLineInput[]=[{accountCode:input.cashAccountCode??'1100',debit:amount,credit:'0.0000'},{accountCode:'1300',debit:'0.0000',credit:amount}];assertBalanced(lines);return{description:'Customer payment',currency:input.currency,lines};}
export function purchaseOnCreditJournal(input:{inventory:string;tax:string;currency:string}):JournalDraft{const inventory=decimalToUnits(input.inventory),tax=decimalToUnits(input.tax);const lines:JournalLineInput[]=[{accountCode:'1400',debit:unitsToDecimal(inventory),credit:'0.0000'},{accountCode:'2100',debit:'0.0000',credit:unitsToDecimal(inventory+tax)}];if(tax>0n)lines.push({accountCode:'2210',debit:unitsToDecimal(tax),credit:'0.0000'});assertBalanced(lines);return{description:'Inventory purchase on credit',currency:input.currency,lines};}
export function supplierPaymentJournal(input:{amount:string;currency:string;cashAccountCode?:string}):JournalDraft{const amount=unitsToDecimal(decimalToUnits(input.amount)),lines:JournalLineInput[]=[{accountCode:'2100',debit:amount,credit:'0.0000'},{accountCode:input.cashAccountCode??'1100',debit:'0.0000',credit:amount}];assertBalanced(lines);return{description:'Supplier payment',currency:input.currency,lines};}
export function expenseJournal(input:{amount:string;tax:string;currency:string;expenseAccountCode?:string;cashAccountCode?:string}):JournalDraft{const amount=decimalToUnits(input.amount),tax=decimalToUnits(input.tax);const lines:JournalLineInput[]=[{accountCode:input.expenseAccountCode??'6000',debit:unitsToDecimal(amount),credit:'0.0000'},{accountCode:input.cashAccountCode??'1100',debit:'0.0000',credit:unitsToDecimal(amount+tax)}];if(tax>0n)lines.push({accountCode:'2210',debit:unitsToDecimal(tax),credit:'0.0000'});assertBalanced(lines);return{description:'Expense paid',currency:input.currency,lines};}

export function saleRefundJournal(input:{net:string;tax:string;cost:string;currency:string;creditAccountCode?:string}):JournalDraft{const net=decimalToUnits(input.net),tax=decimalToUnits(input.tax),cost=decimalToUnits(input.cost);const lines:JournalLineInput[]=[{accountCode:'4100',debit:unitsToDecimal(net),credit:'0.0000'},{accountCode:input.creditAccountCode??'1100',debit:'0.0000',credit:unitsToDecimal(net+tax)}];if(tax>0n)lines.push({accountCode:'2200',debit:unitsToDecimal(tax),credit:'0.0000'});if(cost>0n)lines.push({accountCode:'1400',debit:unitsToDecimal(cost),credit:'0.0000'},{accountCode:'5000',debit:'0.0000',credit:unitsToDecimal(cost)});assertBalanced(lines);return{description:'Sale refund',currency:input.currency,lines};}
