CREATE INDEX "memberships_user_id_status_idx" ON "memberships" ("user_id", "status");
CREATE INDEX "membership_invitations_tenant_id_email_expires_at_idx" ON "membership_invitations" ("tenant_id", "email", "expires_at");
CREATE INDEX "branches_tenant_id_active_idx" ON "branches" ("tenant_id", "active");
CREATE INDEX "subscriptions_status_current_period_ends_at_idx" ON "subscriptions" ("status", "current_period_ends_at");
CREATE INDEX "subscription_events_subscription_id_created_at_idx" ON "subscription_events" ("subscription_id", "created_at");
CREATE INDEX "payments_subscription_id_received_at_idx" ON "payments" ("subscription_id", "received_at");
CREATE INDEX "customers_tenant_id_name_idx" ON "customers" ("tenant_id", "name");
CREATE INDEX "customers_tenant_id_phone_idx" ON "customers" ("tenant_id", "phone");
CREATE INDEX "suppliers_tenant_id_name_idx" ON "suppliers" ("tenant_id", "name");
CREATE INDEX "products_tenant_id_name_idx" ON "products" ("tenant_id", "name");
CREATE INDEX "warehouses_tenant_id_branch_id_idx" ON "warehouses" ("tenant_id", "branch_id");
CREATE INDEX "inventory_movements_tenant_id_warehouse_id_product_id_occurred_" ON "inventory_movements" ("tenant_id", "warehouse_id", "product_id", "occurred_at");
CREATE INDEX "inventory_movements_tenant_id_branch_id_occurred_at_idx" ON "inventory_movements" ("tenant_id", "branch_id", "occurred_at");
CREATE INDEX "sales_invoices_tenant_id_branch_id_created_at_idx" ON "sales_invoices" ("tenant_id", "branch_id", "created_at");
CREATE INDEX "sales_invoices_tenant_id_customer_id_status_idx" ON "sales_invoices" ("tenant_id", "customer_id", "status");
CREATE INDEX "sales_invoice_items_invoice_id_idx" ON "sales_invoice_items" ("invoice_id");
CREATE INDEX "sales_returns_tenant_id_branch_id_created_at_idx" ON "sales_returns" ("tenant_id", "branch_id", "created_at");
CREATE INDEX "customer_payments_tenant_id_customer_id_received_at_idx" ON "customer_payments" ("tenant_id", "customer_id", "received_at");
CREATE INDEX "purchase_bills_tenant_id_branch_id_created_at_idx" ON "purchase_bills" ("tenant_id", "branch_id", "created_at");
CREATE INDEX "purchase_bill_items_bill_id_idx" ON "purchase_bill_items" ("bill_id");
CREATE INDEX "supplier_payments_tenant_id_supplier_id_paid_at_idx" ON "supplier_payments" ("tenant_id", "supplier_id", "paid_at");
CREATE INDEX "expenses_tenant_id_branch_id_occurred_at_idx" ON "expenses" ("tenant_id", "branch_id", "occurred_at");
CREATE INDEX "chart_of_accounts_tenant_id_type_idx" ON "chart_of_accounts" ("tenant_id", "type");
CREATE INDEX "journal_entries_tenant_id_entry_date_status_idx" ON "journal_entries" ("tenant_id", "entry_date", "status");
CREATE INDEX "journal_lines_journal_id_idx" ON "journal_lines" ("journal_id");
CREATE INDEX "journal_lines_account_id_idx" ON "journal_lines" ("account_id");
CREATE INDEX "cashier_shifts_tenant_id_branch_id_status_idx" ON "cashier_shifts" ("tenant_id", "branch_id", "status");
CREATE INDEX "pos_transactions_tenant_id_shift_id_created_at_idx" ON "pos_transactions" ("tenant_id", "shift_id", "created_at");
CREATE INDEX "notifications_tenant_id_user_id_read_at_created_at_idx" ON "notifications" ("tenant_id", "user_id", "read_at", "created_at");
CREATE INDEX "audit_logs_tenant_id_created_at_idx" ON "audit_logs" ("tenant_id", "created_at");
CREATE INDEX "audit_logs_actor_id_created_at_idx" ON "audit_logs" ("actor_id", "created_at");
